# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fdr_c <- function(ProCounts, ProBreaks, ResCounts, ResBreaks, lambda, type_motif) {
    .Call('_DMMD_fdr_c', PACKAGE = 'DMMD', ProCounts, ProBreaks, ResCounts, ResBreaks, lambda, type_motif)
}

cpp_str_sort <- function(in_str, out_str) {
    .Call('_DMMD_cpp_str_sort', PACKAGE = 'DMMD', in_str, out_str)
}

fuse_seqs_c <- function(motif_length, grow_mode, ind_fu, ind_fu_upd, fre_w, sg_w, fre_w_vec, fre_w_next, sg_w_next, fre_w_vec_next, num_cpu) {
    .Call('_DMMD_fuse_seqs_c', PACKAGE = 'DMMD', motif_length, grow_mode, ind_fu, ind_fu_upd, fre_w, sg_w, fre_w_vec, fre_w_next, sg_w_next, fre_w_vec_next, num_cpu)
}

fuse_seqs_seq <- function(motif_length, grow_mode, str_indexes, subindexes, ind_not_void, fre_w, sg_w, fre_w_vec, fre_w_next, sg_w_next, fre_w_vec_next, num_cpu) {
    invisible(.Call('_DMMD_fuse_seqs_seq', PACKAGE = 'DMMD', motif_length, grow_mode, str_indexes, subindexes, ind_not_void, fre_w, sg_w, fre_w_vec, fre_w_next, sg_w_next, fre_w_vec_next, num_cpu))
}

fuse_seqs_openmp <- function(motif_length, grow_mode, str_indexes, subindexes, ind_not_void, fre_w, sg_w, fre_w_vec, fre_w_next, sg_w_next, fre_w_vec_next, num_cpu) {
    invisible(.Call('_DMMD_fuse_seqs_openmp', PACKAGE = 'DMMD', motif_length, grow_mode, str_indexes, subindexes, ind_not_void, fre_w, sg_w, fre_w_vec, fre_w_next, sg_w_next, fre_w_vec_next, num_cpu))
}

find_strings_seq <- function(in_str, out_str) {
    .Call('_DMMD_find_strings_seq', PACKAGE = 'DMMD', in_str, out_str)
}

find_strings_par <- function(in_str, out_str, num_cpu) {
    .Call('_DMMD_find_strings_par', PACKAGE = 'DMMD', in_str, out_str, num_cpu)
}

c_bound_test_openmp <- function(vin, ncores) {
    .Call('_DMMD_c_bound_test_openmp', PACKAGE = 'DMMD', vin, ncores)
}

c_bound_test_seq <- function(vin) {
    .Call('_DMMD_c_bound_test_seq', PACKAGE = 'DMMD', vin)
}

scan_seqs_c <- function(nSeq, LenMot, NumSeq, WeiLogPomElem, WeiLogPWVElem) {
    .Call('_DMMD_scan_seqs_c', PACKAGE = 'DMMD', nSeq, LenMot, NumSeq, WeiLogPomElem, WeiLogPWVElem)
}

