# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fdr_c <- function(ScoDatFraPro, ScoDatFraRes, lambda, type_motif) {
    .Call('_DMMD_fdr_c', PACKAGE = 'DMMD', ScoDatFraPro, ScoDatFraRes, lambda, type_motif)
}

cpp_str_sort <- function(in_str, out_str) {
    .Call('_DMMD_cpp_str_sort', PACKAGE = 'DMMD', in_str, out_str)
}

scan_seqs_c <- function(nSeq, LenMot, NumSeq, WeiLogPomElem, WeiLogPWVElem) {
    .Call('_DMMD_scan_seqs_c', PACKAGE = 'DMMD', nSeq, LenMot, NumSeq, WeiLogPomElem, WeiLogPWVElem)
}

